version: '3'
services:
  application:
    image: file-upload-download
    ports:
      - "9003:9003"
    networks:
      - springboot-db-net
    depends_on:
      - mysqldb
    volumes:
      - /data/springboot-app
    
  mysqldb:
   image: mysql
    networks:
      - springboot-db-net
    #command: --default-authentication-plugin=mysql_native_password
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: basic_project
    volumes:
      - /data/mysql

networks:
  springboot-db-net:
