version: "3"
services:
  application:
    image: file-upload-download

    ports:
      - "9003:9003"
    networks:
      - springboot-uploadFile
    depends_on:
      - db
    volumes:
      - /data/springboot-app

  db:
     image: mysql:5.7
    networks:
      - springboot-uploadFile
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=basicproject
    volumes:
      - /data/mysql
    
networks:
  springboot-uploadFile: 
