version: "3"
services:
  application:
    image: file-upload-download

    ports:
      - "9003:9003"
    networks:
      - springboot-uploadFile
    depends_on:
      - db
    volumes:
      - /data/springboot-uploadFile-app

  db:
    image: mysql
    networks:
      - springboot-uploadFile
    #command: --default-authentication-plugin=mysql_native_password
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: basicproject
    volumes:
      - /data/mysql

networks:
  springboot-uploadFile: 
